// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"
)

const createActivity = `-- name: CreateActivity :exec

INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value, comment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateActivityParams struct {
	ProjectID int64   `db:"project_id"`
	IssueID   *int64  `db:"issue_id"`
	IssueKey  *string `db:"issue_key"`
	ActorID   *int64  `db:"actor_id"`
	Action    string  `db:"action"`
	Field     *string `db:"field"`
	OldValue  *string `db:"old_value"`
	NewValue  *string `db:"new_value"`
	CommentID *int64  `db:"comment_id"`
}

// Activity / audit log. All list queries return the same column set so the service can
// map their rows with one function.
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.Exec(ctx, createActivity,
		arg.ProjectID,
		arg.IssueID,
		arg.IssueKey,
		arg.ActorID,
		arg.Action,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.CommentID,
	)
	return err
}

const listIssueActivities = `-- name: ListIssueActivities :many
SELECT a.id, a.project_id, a.issue_id, a.issue_key, a.actor_id, a.action, a.field, a.old_value, a.new_value, a.created_at, a.comment_id, p.key AS project_key, u.name AS actor_name, u.email AS actor_email,
       COALESCE(left(c.body, $1::int), '')::text AS comment_preview
FROM activities a
JOIN projects p ON p.id = a.project_id
LEFT JOIN users u ON u.id = a.actor_id
LEFT JOIN comments c ON c.id = a.comment_id
WHERE a.issue_id = $2::bigint
ORDER BY a.created_at DESC, a.id DESC
`

type ListIssueActivitiesParams struct {
	CommentPreviewLen int32 `db:"comment_preview_len"`
	IssueID           int64 `db:"issue_id"`
}

type ListIssueActivitiesRow struct {
	Activity       Activity `db:"activity"`
	ProjectKey     string   `db:"project_key"`
	ActorName      *string  `db:"actor_name"`
	ActorEmail     *string  `db:"actor_email"`
	CommentPreview string   `db:"comment_preview"`
}

// The list queries return, as comment_preview, the start of the current body of a
// comment.created row's comment (” for other rows, and once the comment or its issue is
// deleted): text edited out of a comment, or deleted with it, never stays in the history.
func (q *Queries) ListIssueActivities(ctx context.Context, arg ListIssueActivitiesParams) ([]ListIssueActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listIssueActivities, arg.CommentPreviewLen, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueActivitiesRow{}
	for rows.Next() {
		var i ListIssueActivitiesRow
		if err := rows.Scan(
			&i.Activity.ID,
			&i.Activity.ProjectID,
			&i.Activity.IssueID,
			&i.Activity.IssueKey,
			&i.Activity.ActorID,
			&i.Activity.Action,
			&i.Activity.Field,
			&i.Activity.OldValue,
			&i.Activity.NewValue,
			&i.Activity.CreatedAt,
			&i.Activity.CommentID,
			&i.ProjectKey,
			&i.ActorName,
			&i.ActorEmail,
			&i.CommentPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectActivities = `-- name: ListProjectActivities :many
SELECT a.id, a.project_id, a.issue_id, a.issue_key, a.actor_id, a.action, a.field, a.old_value, a.new_value, a.created_at, a.comment_id, p.key AS project_key, u.name AS actor_name, u.email AS actor_email,
       COALESCE(left(c.body, $1::int), '')::text AS comment_preview
FROM activities a
JOIN projects p ON p.id = a.project_id
LEFT JOIN users u ON u.id = a.actor_id
LEFT JOIN comments c ON c.id = a.comment_id
WHERE a.project_id = $2
ORDER BY a.created_at DESC, a.id DESC
LIMIT $4::int OFFSET $3::bigint
`

type ListProjectActivitiesParams struct {
	CommentPreviewLen int32 `db:"comment_preview_len"`
	ProjectID         int64 `db:"project_id"`
	Skip              int64 `db:"skip"`
	MaxResults        int32 `db:"max_results"`
}

type ListProjectActivitiesRow struct {
	Activity       Activity `db:"activity"`
	ProjectKey     string   `db:"project_key"`
	ActorName      *string  `db:"actor_name"`
	ActorEmail     *string  `db:"actor_email"`
	CommentPreview string   `db:"comment_preview"`
}

func (q *Queries) ListProjectActivities(ctx context.Context, arg ListProjectActivitiesParams) ([]ListProjectActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listProjectActivities,
		arg.CommentPreviewLen,
		arg.ProjectID,
		arg.Skip,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectActivitiesRow{}
	for rows.Next() {
		var i ListProjectActivitiesRow
		if err := rows.Scan(
			&i.Activity.ID,
			&i.Activity.ProjectID,
			&i.Activity.IssueID,
			&i.Activity.IssueKey,
			&i.Activity.ActorID,
			&i.Activity.Action,
			&i.Activity.Field,
			&i.Activity.OldValue,
			&i.Activity.NewValue,
			&i.Activity.CreatedAt,
			&i.Activity.CommentID,
			&i.ProjectKey,
			&i.ActorName,
			&i.ActorEmail,
			&i.CommentPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFeedActivities = `-- name: ListUserFeedActivities :many
SELECT a.id, a.project_id, a.issue_id, a.issue_key, a.actor_id, a.action, a.field, a.old_value, a.new_value, a.created_at, a.comment_id, p.key AS project_key, u.name AS actor_name, u.email AS actor_email,
       COALESCE(left(c.body, $1::int), '')::text AS comment_preview
FROM activities a
JOIN projects p ON p.id = a.project_id
LEFT JOIN users u ON u.id = a.actor_id
LEFT JOIN comments c ON c.id = a.comment_id
WHERE a.project_id IN (SELECT pm.project_id FROM project_members pm WHERE pm.user_id = $2)
ORDER BY a.created_at DESC, a.id DESC
LIMIT $4::int OFFSET $3::bigint
`

type ListUserFeedActivitiesParams struct {
	CommentPreviewLen int32 `db:"comment_preview_len"`
	UserID            int64 `db:"user_id"`
	Skip              int64 `db:"skip"`
	MaxResults        int32 `db:"max_results"`
}

type ListUserFeedActivitiesRow struct {
	Activity       Activity `db:"activity"`
	ProjectKey     string   `db:"project_key"`
	ActorName      *string  `db:"actor_name"`
	ActorEmail     *string  `db:"actor_email"`
	CommentPreview string   `db:"comment_preview"`
}

func (q *Queries) ListUserFeedActivities(ctx context.Context, arg ListUserFeedActivitiesParams) ([]ListUserFeedActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserFeedActivities,
		arg.CommentPreviewLen,
		arg.UserID,
		arg.Skip,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserFeedActivitiesRow{}
	for rows.Next() {
		var i ListUserFeedActivitiesRow
		if err := rows.Scan(
			&i.Activity.ID,
			&i.Activity.ProjectID,
			&i.Activity.IssueID,
			&i.Activity.IssueKey,
			&i.Activity.ActorID,
			&i.Activity.Action,
			&i.Activity.Field,
			&i.Activity.OldValue,
			&i.Activity.NewValue,
			&i.Activity.CreatedAt,
			&i.Activity.CommentID,
			&i.ProjectKey,
			&i.ActorName,
			&i.ActorEmail,
			&i.CommentPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
