// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"
)

const createActivity = `-- name: CreateActivity :exec

INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateActivityParams struct {
	ProjectID int64   `db:"project_id"`
	IssueID   *int64  `db:"issue_id"`
	IssueKey  *string `db:"issue_key"`
	ActorID   *int64  `db:"actor_id"`
	Action    string  `db:"action"`
	Field     *string `db:"field"`
	OldValue  *string `db:"old_value"`
	NewValue  *string `db:"new_value"`
}

// Activity / audit log. All list queries return the same column set so the service can
// map their rows with one function.
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.Exec(ctx, createActivity,
		arg.ProjectID,
		arg.IssueID,
		arg.IssueKey,
		arg.ActorID,
		arg.Action,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listIssueActivities = `-- name: ListIssueActivities :many
SELECT a.id, a.project_id, a.issue_id, a.issue_key, a.actor_id, a.action, a.field, a.old_value, a.new_value, a.created_at, p.key AS project_key, u.name AS actor_name, u.email AS actor_email
FROM activities a
JOIN projects p ON p.id = a.project_id
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.issue_id = $1::bigint
ORDER BY a.created_at DESC, a.id DESC
`

type ListIssueActivitiesRow struct {
	Activity   Activity `db:"activity"`
	ProjectKey string   `db:"project_key"`
	ActorName  *string  `db:"actor_name"`
	ActorEmail *string  `db:"actor_email"`
}

func (q *Queries) ListIssueActivities(ctx context.Context, issueID int64) ([]ListIssueActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listIssueActivities, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueActivitiesRow{}
	for rows.Next() {
		var i ListIssueActivitiesRow
		if err := rows.Scan(
			&i.Activity.ID,
			&i.Activity.ProjectID,
			&i.Activity.IssueID,
			&i.Activity.IssueKey,
			&i.Activity.ActorID,
			&i.Activity.Action,
			&i.Activity.Field,
			&i.Activity.OldValue,
			&i.Activity.NewValue,
			&i.Activity.CreatedAt,
			&i.ProjectKey,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectActivities = `-- name: ListProjectActivities :many
SELECT a.id, a.project_id, a.issue_id, a.issue_key, a.actor_id, a.action, a.field, a.old_value, a.new_value, a.created_at, p.key AS project_key, u.name AS actor_name, u.email AS actor_email
FROM activities a
JOIN projects p ON p.id = a.project_id
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.project_id = $1
ORDER BY a.created_at DESC, a.id DESC
LIMIT $3::int OFFSET $2::bigint
`

type ListProjectActivitiesParams struct {
	ProjectID  int64 `db:"project_id"`
	Skip       int64 `db:"skip"`
	MaxResults int32 `db:"max_results"`
}

type ListProjectActivitiesRow struct {
	Activity   Activity `db:"activity"`
	ProjectKey string   `db:"project_key"`
	ActorName  *string  `db:"actor_name"`
	ActorEmail *string  `db:"actor_email"`
}

func (q *Queries) ListProjectActivities(ctx context.Context, arg ListProjectActivitiesParams) ([]ListProjectActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listProjectActivities, arg.ProjectID, arg.Skip, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectActivitiesRow{}
	for rows.Next() {
		var i ListProjectActivitiesRow
		if err := rows.Scan(
			&i.Activity.ID,
			&i.Activity.ProjectID,
			&i.Activity.IssueID,
			&i.Activity.IssueKey,
			&i.Activity.ActorID,
			&i.Activity.Action,
			&i.Activity.Field,
			&i.Activity.OldValue,
			&i.Activity.NewValue,
			&i.Activity.CreatedAt,
			&i.ProjectKey,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFeedActivities = `-- name: ListUserFeedActivities :many
SELECT a.id, a.project_id, a.issue_id, a.issue_key, a.actor_id, a.action, a.field, a.old_value, a.new_value, a.created_at, p.key AS project_key, u.name AS actor_name, u.email AS actor_email
FROM activities a
JOIN projects p ON p.id = a.project_id
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.project_id IN (SELECT pm.project_id FROM project_members pm WHERE pm.user_id = $1)
ORDER BY a.created_at DESC, a.id DESC
LIMIT $3::int OFFSET $2::bigint
`

type ListUserFeedActivitiesParams struct {
	UserID     int64 `db:"user_id"`
	Skip       int64 `db:"skip"`
	MaxResults int32 `db:"max_results"`
}

type ListUserFeedActivitiesRow struct {
	Activity   Activity `db:"activity"`
	ProjectKey string   `db:"project_key"`
	ActorName  *string  `db:"actor_name"`
	ActorEmail *string  `db:"actor_email"`
}

func (q *Queries) ListUserFeedActivities(ctx context.Context, arg ListUserFeedActivitiesParams) ([]ListUserFeedActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserFeedActivities, arg.UserID, arg.Skip, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserFeedActivitiesRow{}
	for rows.Next() {
		var i ListUserFeedActivitiesRow
		if err := rows.Scan(
			&i.Activity.ID,
			&i.Activity.ProjectID,
			&i.Activity.IssueID,
			&i.Activity.IssueKey,
			&i.Activity.ActorID,
			&i.Activity.Action,
			&i.Activity.Field,
			&i.Activity.OldValue,
			&i.Activity.NewValue,
			&i.Activity.CreatedAt,
			&i.ProjectKey,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
