// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package db

import (
	"context"
)

const listBacklogIssues = `-- name: ListBacklogIssues :many
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues i
WHERE i.project_id = $1
  AND i.type IN ('story', 'task', 'bug')
  AND NOT EXISTS (
      SELECT 1 FROM sprints sp, statuses s
      WHERE sp.id = i.sprint_id AND sp.state = 'completed'
        AND s.id = i.status_id AND s.category = 'done'
  )
ORDER BY i.rank, i.id
`

// ListBacklogIssues returns the standard issues (stories, tasks, bugs) shown on the
// backlog page: those without a sprint, those in active or planned sprints, and open
// issues left behind in completed sprints (e.g. reopened after the sprint closed), which
// Jira also lists in the backlog. Done issues of completed sprints are history and are
// excluded. The exclusion must stay NULL-safe: with `NOT (i.sprint_id IN (...) AND ...)`
// a done issue without a sprint would evaluate to NULL and drop out as soon as the
// project has any completed sprint.
func (q *Queries) ListBacklogIssues(ctx context.Context, projectID int64) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listBacklogIssues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpicProgress = `-- name: ListEpicProgress :many
SELECT i.parent_id::bigint AS epic_id,
       count(*)::bigint AS total,
       count(*) FILTER (WHERE s.category = 'done')::bigint AS done,
       count(*) FILTER (WHERE s.category = 'in_progress')::bigint AS in_progress,
       COALESCE(sum(i.story_points), 0)::float8 AS points_total,
       COALESCE(sum(i.story_points) FILTER (WHERE s.category = 'done'), 0)::float8 AS points_done
FROM issues i
JOIN statuses s ON s.id = i.status_id
WHERE i.parent_id = ANY($1::bigint[])
  AND i.type <> 'subtask'
GROUP BY i.parent_id
`

type ListEpicProgressRow struct {
	EpicID      int64   `db:"epic_id"`
	Total       int64   `db:"total"`
	Done        int64   `db:"done"`
	InProgress  int64   `db:"in_progress"`
	PointsTotal float64 `db:"points_total"`
	PointsDone  float64 `db:"points_done"`
}

// ListEpicProgress aggregates each epic's direct children (stories, tasks and bugs) by
// status category. Epics without children have no row.
func (q *Queries) ListEpicProgress(ctx context.Context, epicIds []int64) ([]ListEpicProgressRow, error) {
	rows, err := q.db.Query(ctx, listEpicProgress, epicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpicProgressRow{}
	for rows.Next() {
		var i ListEpicProgressRow
		if err := rows.Scan(
			&i.EpicID,
			&i.Total,
			&i.Done,
			&i.InProgress,
			&i.PointsTotal,
			&i.PointsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanBoardIssues = `-- name: ListKanbanBoardIssues :many
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues i
WHERE i.project_id = $1
  AND i.type <> 'epic'
  AND NOT (
      i.resolved_at IS NOT NULL
      AND i.resolved_at < now() - make_interval(days => $2::int)
      AND i.status_id IN (SELECT s.id FROM statuses s WHERE s.project_id = $1 AND s.category = 'done')
  )
ORDER BY i.rank, i.id
`

type ListKanbanBoardIssuesParams struct {
	ProjectID         int64 `db:"project_id"`
	DoneRetentionDays int32 `db:"done_retention_days"`
}

// ListKanbanBoardIssues returns the issues shown on a Kanban board: every non-epic issue
// of the project except done-category issues resolved more than @done_retention_days
// ago.
func (q *Queries) ListKanbanBoardIssues(ctx context.Context, arg ListKanbanBoardIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listKanbanBoardIssues, arg.ProjectID, arg.DoneRetentionDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectEpics = `-- name: ListProjectEpics :many
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE project_id = $1 AND type = 'epic' ORDER BY rank, id
`

func (q *Queries) ListProjectEpics(ctx context.Context, projectID int64) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listProjectEpics, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintBoardIssues = `-- name: ListSprintBoardIssues :many

SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues
WHERE sprint_id = $1::bigint AND type <> 'epic'
ORDER BY rank, id
`

// Read models for the board, backlog and epics pages (SPEC §2 Boards, §5).
// Every list is in rank order; ties (which only manual SQL can create) break by id.
// ListSprintBoardIssues returns the issues shown on a Scrum board: every non-epic issue
// (standard issues and subtasks) of the sprint.
func (q *Queries) ListSprintBoardIssues(ctx context.Context, sprintID int64) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listSprintBoardIssues, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
