// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one

INSERT INTO comments (issue_id, author_id, body) VALUES ($1, $2, $3) RETURNING id, issue_id, author_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID  int64  `db:"issue_id"`
	AuthorID *int64 `db:"author_id"`
	Body     string `db:"body"`
}

// Issue comments.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.IssueID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, issue_id, author_id, body, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentViews = `-- name: ListCommentViews :many
SELECT c.id, c.issue_id, c.author_id, c.body, c.created_at, c.updated_at, u.name AS author_name, u.email AS author_email
FROM comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.issue_id = $1
ORDER BY c.created_at, c.id
`

type ListCommentViewsRow struct {
	Comment     Comment `db:"comment"`
	AuthorName  *string `db:"author_name"`
	AuthorEmail *string `db:"author_email"`
}

func (q *Queries) ListCommentViews(ctx context.Context, issueID int64) ([]ListCommentViewsRow, error) {
	rows, err := q.db.Query(ctx, listCommentViews, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentViewsRow{}
	for rows.Next() {
		var i ListCommentViewsRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.IssueID,
			&i.Comment.AuthorID,
			&i.Comment.Body,
			&i.Comment.CreatedAt,
			&i.Comment.UpdatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentBody = `-- name: UpdateCommentBody :one
UPDATE comments SET body = $2, updated_at = now() WHERE id = $1 RETURNING id, issue_id, author_id, body, created_at, updated_at
`

type UpdateCommentBodyParams struct {
	ID   int64  `db:"id"`
	Body string `db:"body"`
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentBody, arg.ID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
