// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"
	"time"
)

const countSubtasks = `-- name: CountSubtasks :many
SELECT parent_id::bigint AS parent_id, count(*)::bigint AS subtask_count
FROM issues
WHERE type = 'subtask' AND parent_id = ANY($1::bigint[])
GROUP BY parent_id
`

type CountSubtasksRow struct {
	ParentID     int64 `db:"parent_id"`
	SubtaskCount int64 `db:"subtask_count"`
}

func (q *Queries) CountSubtasks(ctx context.Context, parentIds []int64) ([]CountSubtasksRow, error) {
	rows, err := q.db.Query(ctx, countSubtasks, parentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSubtasksRow{}
	for rows.Next() {
		var i CountSubtasksRow
		if err := rows.Scan(&i.ParentID, &i.SubtaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIssue = `-- name: CreateIssue :one

INSERT INTO issues (
    project_id, number, key, type, summary, description, status_id, priority,
    assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at
`

type CreateIssueParams struct {
	ProjectID   int64      `db:"project_id"`
	Number      int64      `db:"number"`
	Key         string     `db:"key"`
	Type        string     `db:"type"`
	Summary     string     `db:"summary"`
	Description string     `db:"description"`
	StatusID    int64      `db:"status_id"`
	Priority    string     `db:"priority"`
	AssigneeID  *int64     `db:"assignee_id"`
	ReporterID  *int64     `db:"reporter_id"`
	ParentID    *int64     `db:"parent_id"`
	SprintID    *int64     `db:"sprint_id"`
	StoryPoints *float64   `db:"story_points"`
	DueDate     *time.Time `db:"due_date"`
	Rank        string     `db:"rank"`
	ResolvedAt  *time.Time `db:"resolved_at"`
}

// Issues. The dynamic, filterable search lives in internal/service/issue_query.go.
func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Number,
		arg.Key,
		arg.Type,
		arg.Summary,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.AssigneeID,
		arg.ReporterID,
		arg.ParentID,
		arg.SprintID,
		arg.StoryPoints,
		arg.DueDate,
		arg.Rank,
		arg.ResolvedAt,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues WHERE id = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIssue, id)
	return err
}

const getIssueAccessByID = `-- name: GetIssueAccessByID :one
SELECT i.id, i.project_id, i.number, i.key, i.type, i.summary, i.description, i.status_id, i.priority, i.assignee_id, i.reporter_id, i.parent_id, i.sprint_id, i.story_points, i.due_date, i.rank, i.resolved_at, i.created_at, i.updated_at, p.id, p.key, p.name, p.description, p.type, p.lead_id, p.issue_counter, p.created_at, p.updated_at, pm.role
FROM issues i
JOIN projects p ON p.id = i.project_id
JOIN project_members pm ON pm.project_id = i.project_id AND pm.user_id = $1
WHERE i.id = $2
`

type GetIssueAccessByIDParams struct {
	UserID  int64 `db:"user_id"`
	IssueID int64 `db:"issue_id"`
}

type GetIssueAccessByIDRow struct {
	Issue   Issue   `db:"issue"`
	Project Project `db:"project"`
	Role    string  `db:"role"`
}

func (q *Queries) GetIssueAccessByID(ctx context.Context, arg GetIssueAccessByIDParams) (GetIssueAccessByIDRow, error) {
	row := q.db.QueryRow(ctx, getIssueAccessByID, arg.UserID, arg.IssueID)
	var i GetIssueAccessByIDRow
	err := row.Scan(
		&i.Issue.ID,
		&i.Issue.ProjectID,
		&i.Issue.Number,
		&i.Issue.Key,
		&i.Issue.Type,
		&i.Issue.Summary,
		&i.Issue.Description,
		&i.Issue.StatusID,
		&i.Issue.Priority,
		&i.Issue.AssigneeID,
		&i.Issue.ReporterID,
		&i.Issue.ParentID,
		&i.Issue.SprintID,
		&i.Issue.StoryPoints,
		&i.Issue.DueDate,
		&i.Issue.Rank,
		&i.Issue.ResolvedAt,
		&i.Issue.CreatedAt,
		&i.Issue.UpdatedAt,
		&i.Project.ID,
		&i.Project.Key,
		&i.Project.Name,
		&i.Project.Description,
		&i.Project.Type,
		&i.Project.LeadID,
		&i.Project.IssueCounter,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getIssueAccessByKey = `-- name: GetIssueAccessByKey :one
SELECT i.id, i.project_id, i.number, i.key, i.type, i.summary, i.description, i.status_id, i.priority, i.assignee_id, i.reporter_id, i.parent_id, i.sprint_id, i.story_points, i.due_date, i.rank, i.resolved_at, i.created_at, i.updated_at, p.id, p.key, p.name, p.description, p.type, p.lead_id, p.issue_counter, p.created_at, p.updated_at, pm.role
FROM issues i
JOIN projects p ON p.id = i.project_id
JOIN project_members pm ON pm.project_id = i.project_id AND pm.user_id = $1
WHERE i.key = $2
`

type GetIssueAccessByKeyParams struct {
	UserID int64  `db:"user_id"`
	Key    string `db:"key"`
}

type GetIssueAccessByKeyRow struct {
	Issue   Issue   `db:"issue"`
	Project Project `db:"project"`
	Role    string  `db:"role"`
}

// GetIssueAccessByKey returns the issue, its project and the caller's role.
// No row means the issue does not exist or the caller is not a member of its project.
func (q *Queries) GetIssueAccessByKey(ctx context.Context, arg GetIssueAccessByKeyParams) (GetIssueAccessByKeyRow, error) {
	row := q.db.QueryRow(ctx, getIssueAccessByKey, arg.UserID, arg.Key)
	var i GetIssueAccessByKeyRow
	err := row.Scan(
		&i.Issue.ID,
		&i.Issue.ProjectID,
		&i.Issue.Number,
		&i.Issue.Key,
		&i.Issue.Type,
		&i.Issue.Summary,
		&i.Issue.Description,
		&i.Issue.StatusID,
		&i.Issue.Priority,
		&i.Issue.AssigneeID,
		&i.Issue.ReporterID,
		&i.Issue.ParentID,
		&i.Issue.SprintID,
		&i.Issue.StoryPoints,
		&i.Issue.DueDate,
		&i.Issue.Rank,
		&i.Issue.ResolvedAt,
		&i.Issue.CreatedAt,
		&i.Issue.UpdatedAt,
		&i.Project.ID,
		&i.Project.Key,
		&i.Project.Name,
		&i.Project.Description,
		&i.Project.Type,
		&i.Project.LeadID,
		&i.Project.IssueCounter,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueForKeyShare = `-- name: GetIssueForKeyShare :one
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE id = $1 FOR KEY SHARE
`

// GetIssueForKeyShare reads an issue with the lock a foreign-key check takes. Writes that
// insert rows referencing the issue (comments, links, activity) take it when they validate
// the issue, so a concurrent delete either commits first (the row is then gone: 404) or
// waits for the insert — never a foreign-key violation.
func (q *Queries) GetIssueForKeyShare(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueForKeyShare, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueForShare = `-- name: GetIssueForShare :one
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE id = $1 FOR SHARE
`

// GetIssueForShare reads an issue with a share lock held until the end of the transaction:
// a new or re-parented subtask copies its parent's sprint, and the lock keeps that sprint
// from changing (or the parent from being deleted) before the subtask is committed.
func (q *Queries) GetIssueForShare(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueForShare, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildIssues = `-- name: ListChildIssues :many
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE parent_id = $1::bigint ORDER BY rank, id
`

// ListChildIssues returns direct children (epic -> standard issues, standard -> subtasks).
func (q *Queries) ListChildIssues(ctx context.Context, parentID int64) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listChildIssues, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByIDs = `-- name: ListIssuesByIDs :many
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListIssuesByIDs(ctx context.Context, ids []int64) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE parent_id = $1::bigint AND type = 'subtask' ORDER BY rank, id
`

func (q *Queries) ListSubtasks(ctx context.Context, parentID int64) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listSubtasks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Key,
			&i.Type,
			&i.Summary,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.StoryPoints,
			&i.DueDate,
			&i.Rank,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIssue = `-- name: LockIssue :one
SELECT id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at FROM issues WHERE id = $1 FOR NO KEY UPDATE
`

// LockIssue re-reads an issue with a row lock that serialises writers of the issue but not
// inserts that reference it (comments, links, activity rows).
func (q *Queries) LockIssue(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, lockIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logSubtaskSprintSync = `-- name: LogSubtaskSprintSync :exec
INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value)
SELECT st.project_id, st.id, st.key, $1::bigint, 'issue.updated', 'sprint', os.name, ns.name
FROM issues st
JOIN issues par ON par.id = st.parent_id
LEFT JOIN sprints os ON os.id = st.sprint_id
LEFT JOIN sprints ns ON ns.id = par.sprint_id
WHERE st.type = 'subtask'
  AND st.parent_id = ANY($2::bigint[])
  AND st.sprint_id IS DISTINCT FROM par.sprint_id
`

type LogSubtaskSprintSyncParams struct {
	ActorID   int64   `db:"actor_id"`
	ParentIds []int64 `db:"parent_ids"`
}

// LogSubtaskSprintSync records a sprint change for every subtask (of the given parents)
// whose sprint differs from its parent's; run it before SyncSubtaskSprints.
func (q *Queries) LogSubtaskSprintSync(ctx context.Context, arg LogSubtaskSprintSyncParams) error {
	_, err := q.db.Exec(ctx, logSubtaskSprintSync, arg.ActorID, arg.ParentIds)
	return err
}

const logUnparentChildren = `-- name: LogUnparentChildren :exec
INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value)
SELECT i.project_id, i.id, i.key, $1::bigint, 'issue.updated', 'parent', $2::text, NULL
FROM issues i
WHERE i.parent_id = $3::bigint AND i.type <> 'subtask'
`

type LogUnparentChildrenParams struct {
	ActorID   int64  `db:"actor_id"`
	ParentKey string `db:"parent_key"`
	ParentID  int64  `db:"parent_id"`
}

// LogUnparentChildren records the parent change of every non-subtask child of
// `parent_id`; run it before UnparentChildren.
func (q *Queries) LogUnparentChildren(ctx context.Context, arg LogUnparentChildrenParams) error {
	_, err := q.db.Exec(ctx, logUnparentChildren, arg.ActorID, arg.ParentKey, arg.ParentID)
	return err
}

const maxIssueRank = `-- name: MaxIssueRank :one
SELECT COALESCE(MAX(rank), '')::text FROM issues WHERE project_id = $1
`

func (q *Queries) MaxIssueRank(ctx context.Context, projectID int64) (string, error) {
	row := q.db.QueryRow(ctx, maxIssueRank, projectID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const rankAfter = `-- name: RankAfter :one
SELECT COALESCE(MIN(i.rank), '')::text FROM issues i
WHERE i.project_id = $1 AND i.rank > $2::text AND i.id <> $3
`

type RankAfterParams struct {
	ProjectID int64  `db:"project_id"`
	Rank      string `db:"rank"`
	ExcludeID int64  `db:"exclude_id"`
}

// RankAfter returns the smallest rank in the project greater than `rank` (” if none),
// ignoring the issue being moved. Used to keep generated ranks unique project-wide.
func (q *Queries) RankAfter(ctx context.Context, arg RankAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, rankAfter, arg.ProjectID, arg.Rank, arg.ExcludeID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const rankBefore = `-- name: RankBefore :one
SELECT COALESCE(MAX(i.rank), '')::text FROM issues i
WHERE i.project_id = $1 AND i.rank < $2::text AND i.id <> $3
`

type RankBeforeParams struct {
	ProjectID int64  `db:"project_id"`
	Rank      string `db:"rank"`
	ExcludeID int64  `db:"exclude_id"`
}

// RankBefore returns the greatest rank in the project less than `rank` (” if none),
// ignoring the issue being moved.
func (q *Queries) RankBefore(ctx context.Context, arg RankBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, rankBefore, arg.ProjectID, arg.Rank, arg.ExcludeID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const setIssueRank = `-- name: SetIssueRank :one
UPDATE issues SET rank = $2 WHERE id = $1 RETURNING id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at
`

type SetIssueRankParams struct {
	ID   int64  `db:"id"`
	Rank string `db:"rank"`
}

// SetIssueRank changes only the rank (rank-only moves do not touch updated_at).
func (q *Queries) SetIssueRank(ctx context.Context, arg SetIssueRankParams) (Issue, error) {
	row := q.db.QueryRow(ctx, setIssueRank, arg.ID, arg.Rank)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const syncSubtaskSprints = `-- name: SyncSubtaskSprints :execrows
UPDATE issues st
SET sprint_id = par.sprint_id, updated_at = now()
FROM issues par
WHERE par.id = st.parent_id
  AND st.type = 'subtask'
  AND st.parent_id = ANY($1::bigint[])
  AND st.sprint_id IS DISTINCT FROM par.sprint_id
`

// SyncSubtaskSprints sets each subtask's sprint to its parent's sprint.
func (q *Queries) SyncSubtaskSprints(ctx context.Context, parentIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, syncSubtaskSprints, parentIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unparentChildren = `-- name: UnparentChildren :exec
UPDATE issues SET parent_id = NULL, updated_at = now()
WHERE parent_id = $1::bigint AND type <> 'subtask'
`

func (q *Queries) UnparentChildren(ctx context.Context, parentID int64) error {
	_, err := q.db.Exec(ctx, unparentChildren, parentID)
	return err
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues
SET type         = $2,
    summary      = $3,
    description  = $4,
    status_id    = $5,
    priority     = $6,
    assignee_id  = $7,
    reporter_id  = $8,
    parent_id    = $9,
    sprint_id    = $10,
    story_points = $11,
    due_date     = $12,
    resolved_at  = $13,
    updated_at   = now()
WHERE id = $1
RETURNING id, project_id, number, key, type, summary, description, status_id, priority, assignee_id, reporter_id, parent_id, sprint_id, story_points, due_date, rank, resolved_at, created_at, updated_at
`

type UpdateIssueParams struct {
	ID          int64      `db:"id"`
	Type        string     `db:"type"`
	Summary     string     `db:"summary"`
	Description string     `db:"description"`
	StatusID    int64      `db:"status_id"`
	Priority    string     `db:"priority"`
	AssigneeID  *int64     `db:"assignee_id"`
	ReporterID  *int64     `db:"reporter_id"`
	ParentID    *int64     `db:"parent_id"`
	SprintID    *int64     `db:"sprint_id"`
	StoryPoints *float64   `db:"story_points"`
	DueDate     *time.Time `db:"due_date"`
	ResolvedAt  *time.Time `db:"resolved_at"`
}

// UpdateIssue writes every mutable column and bumps updated_at.
func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.ID,
		arg.Type,
		arg.Summary,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.AssigneeID,
		arg.ReporterID,
		arg.ParentID,
		arg.SprintID,
		arg.StoryPoints,
		arg.DueDate,
		arg.ResolvedAt,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Summary,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.StoryPoints,
		&i.DueDate,
		&i.Rank,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
