// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"
)

const addIssueLabels = `-- name: AddIssueLabels :exec
INSERT INTO issue_labels (issue_id, label_id)
SELECT $1::bigint, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddIssueLabelsParams struct {
	IssueID  int64   `db:"issue_id"`
	LabelIds []int64 `db:"label_ids"`
}

func (q *Queries) AddIssueLabels(ctx context.Context, arg AddIssueLabelsParams) error {
	_, err := q.db.Exec(ctx, addIssueLabels, arg.IssueID, arg.LabelIds)
	return err
}

const clearIssueLabels = `-- name: ClearIssueLabels :exec
DELETE FROM issue_labels WHERE issue_id = $1
`

func (q *Queries) ClearIssueLabels(ctx context.Context, issueID int64) error {
	_, err := q.db.Exec(ctx, clearIssueLabels, issueID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (project_id, name, color) VALUES ($1, $2, $3) RETURNING id, project_id, name, color, created_at
`

type CreateLabelParams struct {
	ProjectID int64  `db:"project_id"`
	Name      string `db:"name"`
	Color     string `db:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.ProjectID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT id, project_id, name, color, created_at FROM labels WHERE id = $1
`

func (q *Queries) GetLabel(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listIssueLabels = `-- name: ListIssueLabels :many
SELECT il.issue_id, l.id, l.project_id, l.name, l.color, l.created_at
FROM issue_labels il
JOIN labels l ON l.id = il.label_id
WHERE il.issue_id = ANY($1::bigint[])
ORDER BY il.issue_id, lower(l.name) COLLATE "und-x-icu", l.id
`

type ListIssueLabelsRow struct {
	IssueID int64 `db:"issue_id"`
	Label   Label `db:"label"`
}

func (q *Queries) ListIssueLabels(ctx context.Context, issueIds []int64) ([]ListIssueLabelsRow, error) {
	rows, err := q.db.Query(ctx, listIssueLabels, issueIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueLabelsRow{}
	for rows.Next() {
		var i ListIssueLabelsRow
		if err := rows.Scan(
			&i.IssueID,
			&i.Label.ID,
			&i.Label.ProjectID,
			&i.Label.Name,
			&i.Label.Color,
			&i.Label.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many

SELECT id, project_id, name, color, created_at FROM labels WHERE project_id = $1 ORDER BY lower(name) COLLATE "und-x-icu", id
`

// Labels and issue <-> label assignments. Labels are always ordered by name, case-insensitively
// and in the Unicode root collation ("und-x-icu", so accented letters sort with their base
// letter whatever the database's default collation is).
func (q *Queries) ListLabels(ctx context.Context, projectID int64) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLabel = `-- name: LockLabel :one
SELECT id, project_id, name, color, created_at FROM labels WHERE id = $1 FOR NO KEY UPDATE
`

// LockLabel locks a label that is about to be renamed or recoloured, so concurrent edits
// apply one after the other and each keeps the other's change. FOR NO KEY UPDATE does not
// block issue writes assigning the label (LockLabelsByIDs).
func (q *Queries) LockLabel(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRow(ctx, lockLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const lockLabelsByIDs = `-- name: LockLabelsByIDs :many
SELECT id, project_id, name, color, created_at FROM labels WHERE id = ANY($1::bigint[]) ORDER BY lower(name) COLLATE "und-x-icu", id FOR KEY SHARE
`

// LockLabelsByIDs loads labels with the lock a foreign-key check takes: issue writes
// assigning labels use it, so a label deleted concurrently is either gone when the write
// validates it or its delete waits until the assignment has committed.
func (q *Queries) LockLabelsByIDs(ctx context.Context, ids []int64) ([]Label, error) {
	rows, err := q.db.Query(ctx, lockLabelsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels SET name = $2, color = $3 WHERE id = $1 RETURNING id, project_id, name, color, created_at
`

type UpdateLabelParams struct {
	ID    int64  `db:"id"`
	Name  string `db:"name"`
	Color string `db:"color"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel, arg.ID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
