// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const createIssueLink = `-- name: CreateIssueLink :one

INSERT INTO issue_links (type, source_id, target_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, type, source_id, target_id, created_by, created_at
`

type CreateIssueLinkParams struct {
	Type      string `db:"type"`
	SourceID  int64  `db:"source_id"`
	TargetID  int64  `db:"target_id"`
	CreatedBy *int64 `db:"created_by"`
}

// Issue links. source_id is the outward side ("GB-1 blocks GB-2": source = GB-1).
func (q *Queries) CreateIssueLink(ctx context.Context, arg CreateIssueLinkParams) (IssueLink, error) {
	row := q.db.QueryRow(ctx, createIssueLink,
		arg.Type,
		arg.SourceID,
		arg.TargetID,
		arg.CreatedBy,
	)
	var i IssueLink
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SourceID,
		&i.TargetID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIssueLink = `-- name: DeleteIssueLink :execrows
DELETE FROM issue_links WHERE id = $1
`

// DeleteIssueLink returns the number of links deleted: 0 when a concurrent delete won.
func (q *Queries) DeleteIssueLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIssueLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIssueLink = `-- name: GetIssueLink :one
SELECT id, type, source_id, target_id, created_by, created_at FROM issue_links WHERE id = $1
`

func (q *Queries) GetIssueLink(ctx context.Context, id int64) (IssueLink, error) {
	row := q.db.QueryRow(ctx, getIssueLink, id)
	var i IssueLink
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SourceID,
		&i.TargetID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const issueLinkExists = `-- name: IssueLinkExists :one
SELECT EXISTS (
    SELECT 1 FROM issue_links WHERE type = $1 AND source_id = $2 AND target_id = $3
)
`

type IssueLinkExistsParams struct {
	Type     string `db:"type"`
	SourceID int64  `db:"source_id"`
	TargetID int64  `db:"target_id"`
}

// IssueLinkExists reports whether a link of `type` exists from source to target.
func (q *Queries) IssueLinkExists(ctx context.Context, arg IssueLinkExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, issueLinkExists, arg.Type, arg.SourceID, arg.TargetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listIssueLinks = `-- name: ListIssueLinks :many
SELECT id, type, source_id, target_id, created_by, created_at FROM issue_links WHERE source_id = $1 OR target_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListIssueLinks(ctx context.Context, sourceID int64) ([]IssueLink, error) {
	rows, err := q.db.Query(ctx, listIssueLinks, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueLink{}
	for rows.Next() {
		var i IssueLink
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.SourceID,
			&i.TargetID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
