// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
	"time"
)

const addMember = `-- name: AddMember :one

INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, role, created_at
`

type AddMemberParams struct {
	ProjectID int64  `db:"project_id"`
	UserID    int64  `db:"user_id"`
	Role      string `db:"role"`
}

// Project members.
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countProjectAdmins = `-- name: CountProjectAdmins :one
SELECT count(*) FROM project_members WHERE project_id = $1 AND role = 'admin'
`

func (q *Queries) CountProjectAdmins(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectAdmins, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	ProjectID int64 `db:"project_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ProjectID, arg.UserID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT project_id, user_id, role, created_at FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	ProjectID int64 `db:"project_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (SELECT 1 FROM project_members WHERE project_id = $1 AND user_id = $2)
`

type IsProjectMemberParams struct {
	ProjectID int64 `db:"project_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMemberProjectIDs = `-- name: ListMemberProjectIDs :many
SELECT project_id FROM project_members WHERE user_id = $1
`

func (q *Queries) ListMemberProjectIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMemberProjectIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var project_id int64
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberProjectKeys = `-- name: ListMemberProjectKeys :many
SELECT p.key FROM project_members pm JOIN projects p ON p.id = pm.project_id WHERE pm.user_id = $1
`

func (q *Queries) ListMemberProjectKeys(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listMemberProjectKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberViews = `-- name: ListMemberViews :many
SELECT pm.user_id, pm.role, pm.created_at, u.name, u.email
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
  AND ($2::bigint IS NULL OR pm.user_id = $2::bigint)
ORDER BY lower(u.name) COLLATE "und-x-icu", u.id
`

type ListMemberViewsParams struct {
	ProjectID int64  `db:"project_id"`
	UserID    *int64 `db:"user_id"`
}

type ListMemberViewsRow struct {
	UserID    int64     `db:"user_id"`
	Role      string    `db:"role"`
	CreatedAt time.Time `db:"created_at"`
	Name      string    `db:"name"`
	Email     string    `db:"email"`
}

// ListMemberViews returns members with their user data ordered by name (optionally one user),
// in the Unicode root collation like every name-ordered list (see labels.sql).
func (q *Queries) ListMemberViews(ctx context.Context, arg ListMemberViewsParams) ([]ListMemberViewsRow, error) {
	rows, err := q.db.Query(ctx, listMemberViews, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberViewsRow{}
	for rows.Next() {
		var i ListMemberViewsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logUnassignMemberIssues = `-- name: LogUnassignMemberIssues :exec
INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value)
SELECT i.project_id, i.id, i.key, $1::bigint, 'issue.updated', 'assignee', u.name, NULL
FROM issues i
JOIN users u ON u.id = i.assignee_id
WHERE i.project_id = $2 AND i.assignee_id = $3::bigint
`

type LogUnassignMemberIssuesParams struct {
	ActorID   int64 `db:"actor_id"`
	ProjectID int64 `db:"project_id"`
	UserID    int64 `db:"user_id"`
}

// LogUnassignMemberIssues records an assignee change for every issue about to be
// unassigned by UnassignMemberIssues. Run it first.
func (q *Queries) LogUnassignMemberIssues(ctx context.Context, arg LogUnassignMemberIssuesParams) error {
	_, err := q.db.Exec(ctx, logUnassignMemberIssues, arg.ActorID, arg.ProjectID, arg.UserID)
	return err
}

const unassignMemberIssues = `-- name: UnassignMemberIssues :exec
UPDATE issues SET assignee_id = NULL, updated_at = now()
WHERE project_id = $1 AND assignee_id = $2::bigint
`

type UnassignMemberIssuesParams struct {
	ProjectID int64 `db:"project_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) UnassignMemberIssues(ctx context.Context, arg UnassignMemberIssuesParams) error {
	_, err := q.db.Exec(ctx, unassignMemberIssues, arg.ProjectID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE project_members SET role = $3 WHERE project_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	ProjectID int64  `db:"project_id"`
	UserID    int64  `db:"user_id"`
	Role      string `db:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
