// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Activity struct {
	ID        int64     `db:"id"`
	ProjectID int64     `db:"project_id"`
	IssueID   *int64    `db:"issue_id"`
	IssueKey  *string   `db:"issue_key"`
	ActorID   *int64    `db:"actor_id"`
	Action    string    `db:"action"`
	Field     *string   `db:"field"`
	OldValue  *string   `db:"old_value"`
	NewValue  *string   `db:"new_value"`
	CreatedAt time.Time `db:"created_at"`
	CommentID *int64    `db:"comment_id"`
}

type Comment struct {
	ID        int64     `db:"id"`
	IssueID   int64     `db:"issue_id"`
	AuthorID  *int64    `db:"author_id"`
	Body      string    `db:"body"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type Issue struct {
	ID          int64      `db:"id"`
	ProjectID   int64      `db:"project_id"`
	Number      int64      `db:"number"`
	Key         string     `db:"key"`
	Type        string     `db:"type"`
	Summary     string     `db:"summary"`
	Description string     `db:"description"`
	StatusID    int64      `db:"status_id"`
	Priority    string     `db:"priority"`
	AssigneeID  *int64     `db:"assignee_id"`
	ReporterID  *int64     `db:"reporter_id"`
	ParentID    *int64     `db:"parent_id"`
	SprintID    *int64     `db:"sprint_id"`
	StoryPoints *float64   `db:"story_points"`
	DueDate     *time.Time `db:"due_date"`
	Rank        string     `db:"rank"`
	ResolvedAt  *time.Time `db:"resolved_at"`
	CreatedAt   time.Time  `db:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at"`
}

type IssueLabel struct {
	IssueID int64 `db:"issue_id"`
	LabelID int64 `db:"label_id"`
}

type IssueLink struct {
	ID        int64     `db:"id"`
	Type      string    `db:"type"`
	SourceID  int64     `db:"source_id"`
	TargetID  int64     `db:"target_id"`
	CreatedBy *int64    `db:"created_by"`
	CreatedAt time.Time `db:"created_at"`
}

type Label struct {
	ID        int64     `db:"id"`
	ProjectID int64     `db:"project_id"`
	Name      string    `db:"name"`
	Color     string    `db:"color"`
	CreatedAt time.Time `db:"created_at"`
}

type Project struct {
	ID           int64     `db:"id"`
	Key          string    `db:"key"`
	Name         string    `db:"name"`
	Description  string    `db:"description"`
	Type         string    `db:"type"`
	LeadID       *int64    `db:"lead_id"`
	IssueCounter int64     `db:"issue_counter"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type ProjectMember struct {
	ProjectID int64     `db:"project_id"`
	UserID    int64     `db:"user_id"`
	Role      string    `db:"role"`
	CreatedAt time.Time `db:"created_at"`
}

type Sprint struct {
	ID          int64      `db:"id"`
	ProjectID   int64      `db:"project_id"`
	Name        string     `db:"name"`
	Goal        string     `db:"goal"`
	State       string     `db:"state"`
	StartDate   *time.Time `db:"start_date"`
	EndDate     *time.Time `db:"end_date"`
	CompletedAt *time.Time `db:"completed_at"`
	CreatedAt   time.Time  `db:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at"`
}

type Status struct {
	ID        int64     `db:"id"`
	ProjectID int64     `db:"project_id"`
	Name      string    `db:"name"`
	Category  string    `db:"category"`
	Position  int32     `db:"position"`
	WipLimit  *int32    `db:"wip_limit"`
	CreatedAt time.Time `db:"created_at"`
}

type User struct {
	ID           int64     `db:"id"`
	Email        string    `db:"email"`
	Name         string    `db:"name"`
	PasswordHash string    `db:"password_hash"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
	TokenVersion int32     `db:"token_version"`
}
