// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const clearProjectLead = `-- name: ClearProjectLead :exec
UPDATE projects SET lead_id = NULL, updated_at = now() WHERE id = $1 AND lead_id = $2::bigint
`

type ClearProjectLeadParams struct {
	ProjectID int64 `db:"project_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) ClearProjectLead(ctx context.Context, arg ClearProjectLeadParams) error {
	_, err := q.db.Exec(ctx, clearProjectLead, arg.ProjectID, arg.UserID)
	return err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (key, name, description, type, lead_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, key, name, description, type, lead_id, issue_counter, created_at, updated_at
`

type CreateProjectParams struct {
	Key         string `db:"key"`
	Name        string `db:"name"`
	Description string `db:"description"`
	Type        string `db:"type"`
	LeadID      *int64 `db:"lead_id"`
}

// Projects and project membership lookups used for permission checks.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.LeadID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.LeadID,
		&i.IssueCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectAccessByID = `-- name: GetProjectAccessByID :one
SELECT p.id, p.key, p.name, p.description, p.type, p.lead_id, p.issue_counter, p.created_at, p.updated_at, pm.role
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $1
WHERE p.id = $2
`

type GetProjectAccessByIDParams struct {
	UserID    int64 `db:"user_id"`
	ProjectID int64 `db:"project_id"`
}

type GetProjectAccessByIDRow struct {
	Project Project `db:"project"`
	Role    string  `db:"role"`
}

func (q *Queries) GetProjectAccessByID(ctx context.Context, arg GetProjectAccessByIDParams) (GetProjectAccessByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectAccessByID, arg.UserID, arg.ProjectID)
	var i GetProjectAccessByIDRow
	err := row.Scan(
		&i.Project.ID,
		&i.Project.Key,
		&i.Project.Name,
		&i.Project.Description,
		&i.Project.Type,
		&i.Project.LeadID,
		&i.Project.IssueCounter,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getProjectAccessByKey = `-- name: GetProjectAccessByKey :one
SELECT p.id, p.key, p.name, p.description, p.type, p.lead_id, p.issue_counter, p.created_at, p.updated_at, pm.role
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $1
WHERE p.key = $2
`

type GetProjectAccessByKeyParams struct {
	UserID int64  `db:"user_id"`
	Key    string `db:"key"`
}

type GetProjectAccessByKeyRow struct {
	Project Project `db:"project"`
	Role    string  `db:"role"`
}

// GetProjectAccessByKey returns the project together with the caller's role.
// No row means the project does not exist or the caller is not a member.
func (q *Queries) GetProjectAccessByKey(ctx context.Context, arg GetProjectAccessByKeyParams) (GetProjectAccessByKeyRow, error) {
	row := q.db.QueryRow(ctx, getProjectAccessByKey, arg.UserID, arg.Key)
	var i GetProjectAccessByKeyRow
	err := row.Scan(
		&i.Project.ID,
		&i.Project.Key,
		&i.Project.Name,
		&i.Project.Description,
		&i.Project.Type,
		&i.Project.LeadID,
		&i.Project.IssueCounter,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, key, name, description, type, lead_id, issue_counter, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.LeadID,
		&i.IssueCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectViews = `-- name: ListProjectViews :many
SELECT p.id, p.key, p.name, p.description, p.type, p.lead_id, p.issue_counter, p.created_at, p.updated_at,
       pm.role,
       (SELECT count(*) FROM issues i WHERE i.project_id = p.id)::bigint AS issue_count,
       u.name  AS lead_name,
       u.email AS lead_email
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $1
LEFT JOIN users u ON u.id = p.lead_id
WHERE ($2::bigint IS NULL OR p.id = $2::bigint)
ORDER BY lower(p.name), p.id
`

type ListProjectViewsParams struct {
	UserID    int64  `db:"user_id"`
	ProjectID *int64 `db:"project_id"`
}

type ListProjectViewsRow struct {
	Project    Project `db:"project"`
	Role       string  `db:"role"`
	IssueCount int64   `db:"issue_count"`
	LeadName   *string `db:"lead_name"`
	LeadEmail  *string `db:"lead_email"`
}

// ListProjectViews returns everything needed to render Project DTOs for the projects the
// user belongs to (optionally restricted to one project).
func (q *Queries) ListProjectViews(ctx context.Context, arg ListProjectViewsParams) ([]ListProjectViewsRow, error) {
	rows, err := q.db.Query(ctx, listProjectViews, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectViewsRow{}
	for rows.Next() {
		var i ListProjectViewsRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.Key,
			&i.Project.Name,
			&i.Project.Description,
			&i.Project.Type,
			&i.Project.LeadID,
			&i.Project.IssueCounter,
			&i.Project.CreatedAt,
			&i.Project.UpdatedAt,
			&i.Role,
			&i.IssueCount,
			&i.LeadName,
			&i.LeadEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProject = `-- name: LockProject :exec
SELECT id FROM projects WHERE id = $1 FOR NO KEY UPDATE
`

// LockProject takes a row lock on the project; used to serialise rank computations,
// admin-count checks and sprint lifecycle changes inside a transaction. FOR NO KEY UPDATE
// (like the implicit lock of NextIssueNumber) still lets other transactions insert rows
// that reference the project: a plain FOR UPDATE would also block their foreign-key checks
// and deadlock with writers that hold an issue lock while logging activity.
func (q *Queries) LockProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockProject, id)
	return err
}

const nextIssueNumber = `-- name: NextIssueNumber :one
UPDATE projects SET issue_counter = issue_counter + 1 WHERE id = $1 RETURNING issue_counter
`

// NextIssueNumber atomically reserves the next issue number (and locks the project row
// until the surrounding transaction ends).
func (q *Queries) NextIssueNumber(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextIssueNumber, id)
	var issue_counter int64
	err := row.Scan(&issue_counter)
	return issue_counter, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, type = $4, lead_id = $5, updated_at = now()
WHERE id = $1
RETURNING id, key, name, description, type, lead_id, issue_counter, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          int64  `db:"id"`
	Name        string `db:"name"`
	Description string `db:"description"`
	Type        string `db:"type"`
	LeadID      *int64 `db:"lead_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.LeadID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.LeadID,
		&i.IssueCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
