// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprints.sql

package db

import (
	"context"
	"time"
)

const completeSprint = `-- name: CompleteSprint :one
UPDATE sprints
SET state = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at
`

func (q *Queries) CompleteSprint(ctx context.Context, id int64) (Sprint, error) {
	row := q.db.QueryRow(ctx, completeSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countSprintsCreated = `-- name: CountSprintsCreated :one
SELECT GREATEST(
    (SELECT count(*) FROM activities a WHERE a.project_id = $1 AND a.action = 'sprint.created'),
    (SELECT count(*) FROM sprints s WHERE s.project_id = $1)
)::bigint
`

// CountSprintsCreated is the number of sprints ever created in a project, used for default
// sprint names. sprint.created activity rows outlive deleted sprints; the row count covers
// sprints inserted without an activity row.
func (q *Queries) CountSprintsCreated(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSprintsCreated, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (project_id, name, goal, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at
`

type CreateSprintParams struct {
	ProjectID int64      `db:"project_id"`
	Name      string     `db:"name"`
	Goal      string     `db:"goal"`
	StartDate *time.Time `db:"start_date"`
	EndDate   *time.Time `db:"end_date"`
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ProjectID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSprint = `-- name: DeleteSprint :exec
DELETE FROM sprints WHERE id = $1
`

func (q *Queries) DeleteSprint(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSprint, id)
	return err
}

const getActiveSprint = `-- name: GetActiveSprint :one
SELECT id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at FROM sprints WHERE project_id = $1 AND state = 'active'
`

func (q *Queries) GetActiveSprint(ctx context.Context, projectID int64) (Sprint, error) {
	row := q.db.QueryRow(ctx, getActiveSprint, projectID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprint = `-- name: GetSprint :one

SELECT id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at FROM sprints WHERE id = $1
`

// Sprints (Scrum) and their lifecycle: planned -> active -> completed.
func (q *Queries) GetSprint(ctx context.Context, id int64) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprintForShare = `-- name: GetSprintForShare :one
SELECT id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at FROM sprints WHERE id = $1 FOR SHARE
`

// GetSprintForShare reads a sprint with a FOR SHARE lock: issue writes that put an issue
// into a sprint take it, so they serialise with sprint lifecycle changes (LockSprint) and
// never add issues to a sprint that is being completed or deleted.
func (q *Queries) GetSprintForShare(ctx context.Context, id int64) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprintForShare, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectSprints = `-- name: ListProjectSprints :many
SELECT id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at FROM sprints
WHERE project_id = $1
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR state = ANY($2::text[]))
ORDER BY CASE state WHEN 'active' THEN 0 WHEN 'planned' THEN 1 ELSE 2 END,
         CASE WHEN state = 'planned' THEN id END,
         completed_at DESC NULLS LAST,
         id DESC
`

type ListProjectSprintsParams struct {
	ProjectID int64    `db:"project_id"`
	States    []string `db:"states"`
}

// ListProjectSprints lists a project's sprints, optionally restricted to some states (an
// empty array means all), ordered as the UI shows them: the active sprint first, then
// planned sprints by creation (id), then completed sprints, most recently completed first.
func (q *Queries) ListProjectSprints(ctx context.Context, arg ListProjectSprintsParams) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listProjectSprints, arg.ProjectID, arg.States)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Goal,
			&i.State,
			&i.StartDate,
			&i.EndDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintNames = `-- name: ListSprintNames :many
SELECT name FROM sprints WHERE project_id = $1
`

func (q *Queries) ListSprintNames(ctx context.Context, projectID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listSprintNames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintStandardIssues = `-- name: ListSprintStandardIssues :many
SELECT i.id, (SELECT s.category FROM statuses s WHERE s.id = i.status_id)::text AS category
FROM issues i
WHERE i.sprint_id = $1::bigint
  AND i.type IN ('story', 'task', 'bug')
ORDER BY i.rank, i.id
FOR NO KEY UPDATE
`

type ListSprintStandardIssuesRow struct {
	ID       int64  `db:"id"`
	Category string `db:"category"`
}

// ListSprintStandardIssues returns the standard issues of a sprint (the ones that carry
// their subtasks along when they change sprint) with their status category, locking them
// for the rest of the transaction. A row locked by a concurrent writer is re-checked once
// that writer commits (READ COMMITTED's EvalPlanQual): an issue moved out of the sprint or
// deleted drops out, and an issue whose status changed is returned with its new category.
// The category must come from a correlated subquery, not a join: the re-check does not
// re-fetch a joined statuses row for the new status_id, so with a join a re-statused issue
// would silently vanish from the result (and stay behind in a completed sprint).
func (q *Queries) ListSprintStandardIssues(ctx context.Context, sprintID int64) ([]ListSprintStandardIssuesRow, error) {
	rows, err := q.db.Query(ctx, listSprintStandardIssues, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintStandardIssuesRow{}
	for rows.Next() {
		var i ListSprintStandardIssuesRow
		if err := rows.Scan(&i.ID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintStats = `-- name: ListSprintStats :many
SELECT i.sprint_id::bigint AS sprint_id,
       count(*)::bigint AS issue_count,
       COALESCE(sum(i.story_points), 0)::float8 AS points_total,
       COALESCE(sum(i.story_points) FILTER (WHERE s.category = 'done'), 0)::float8 AS points_done
FROM issues i
JOIN statuses s ON s.id = i.status_id
WHERE i.sprint_id = ANY($1::bigint[])
  AND i.type IN ('story', 'task', 'bug')
GROUP BY i.sprint_id
`

type ListSprintStatsRow struct {
	SprintID    int64   `db:"sprint_id"`
	IssueCount  int64   `db:"issue_count"`
	PointsTotal float64 `db:"points_total"`
	PointsDone  float64 `db:"points_done"`
}

// ListSprintStats returns, per sprint, the SPEC §4 Sprint statistics over its standard
// issues (stories, tasks and bugs; subtasks and epics are not counted). Sprints without
// issues have no row.
func (q *Queries) ListSprintStats(ctx context.Context, sprintIds []int64) ([]ListSprintStatsRow, error) {
	rows, err := q.db.Query(ctx, listSprintStats, sprintIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintStatsRow{}
	for rows.Next() {
		var i ListSprintStatsRow
		if err := rows.Scan(
			&i.SprintID,
			&i.IssueCount,
			&i.PointsTotal,
			&i.PointsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByIDs = `-- name: ListSprintsByIDs :many
SELECT id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at FROM sprints WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListSprintsByIDs(ctx context.Context, ids []int64) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Goal,
			&i.State,
			&i.StartDate,
			&i.EndDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSprint = `-- name: LockSprint :one
SELECT id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at FROM sprints WHERE id = $1 FOR NO KEY UPDATE
`

// LockSprint locks a sprint for a lifecycle change. FOR NO KEY UPDATE conflicts with
// GetSprintForShare but not with foreign-key checks of issue rows.
func (q *Queries) LockSprint(ctx context.Context, id int64) (Sprint, error) {
	row := q.db.QueryRow(ctx, lockSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logIssueSprintChanges = `-- name: LogIssueSprintChanges :exec
INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value)
SELECT i.project_id, i.id, i.key, $1::bigint, 'issue.updated', 'sprint', os.name, ns.name
FROM issues i
LEFT JOIN sprints os ON os.id = i.sprint_id
LEFT JOIN sprints ns ON ns.id = $2::bigint
WHERE i.id = ANY($3::bigint[])
  AND i.sprint_id IS DISTINCT FROM $2::bigint
ORDER BY i.rank, i.id
`

type LogIssueSprintChangesParams struct {
	ActorID  int64   `db:"actor_id"`
	SprintID *int64  `db:"sprint_id"`
	IssueIds []int64 `db:"issue_ids"`
}

// LogIssueSprintChanges records a sprint change (old -> new sprint name; null = backlog)
// for every listed issue whose sprint differs from the target. Run it before
// SetIssuesSprint.
func (q *Queries) LogIssueSprintChanges(ctx context.Context, arg LogIssueSprintChangesParams) error {
	_, err := q.db.Exec(ctx, logIssueSprintChanges, arg.ActorID, arg.SprintID, arg.IssueIds)
	return err
}

const setIssuesSprint = `-- name: SetIssuesSprint :exec
UPDATE issues
SET sprint_id = $1::bigint, updated_at = now()
WHERE id = ANY($2::bigint[])
  AND sprint_id IS DISTINCT FROM $1::bigint
`

type SetIssuesSprintParams struct {
	SprintID *int64  `db:"sprint_id"`
	IssueIds []int64 `db:"issue_ids"`
}

// SetIssuesSprint moves the listed issues to a sprint (null = backlog).
func (q *Queries) SetIssuesSprint(ctx context.Context, arg SetIssuesSprintParams) error {
	_, err := q.db.Exec(ctx, setIssuesSprint, arg.SprintID, arg.IssueIds)
	return err
}

const startSprint = `-- name: StartSprint :one
UPDATE sprints
SET state = 'active', name = $2, goal = $3, start_date = $4, end_date = $5, updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at
`

type StartSprintParams struct {
	ID        int64      `db:"id"`
	Name      string     `db:"name"`
	Goal      string     `db:"goal"`
	StartDate *time.Time `db:"start_date"`
	EndDate   *time.Time `db:"end_date"`
}

func (q *Queries) StartSprint(ctx context.Context, arg StartSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, startSprint,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET name = $2, goal = $3, start_date = $4, end_date = $5, updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, goal, state, start_date, end_date, completed_at, created_at, updated_at
`

type UpdateSprintParams struct {
	ID        int64      `db:"id"`
	Name      string     `db:"name"`
	Goal      string     `db:"goal"`
	StartDate *time.Time `db:"start_date"`
	EndDate   *time.Time `db:"end_date"`
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.State,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
