// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package db

import (
	"context"
)

const compactStatusPositions = `-- name: CompactStatusPositions :exec
UPDATE statuses s
SET position = r.pos
FROM (
    SELECT s2.id, (row_number() OVER (ORDER BY s2.position, s2.id) - 1)::int AS pos
    FROM statuses s2
    WHERE s2.project_id = $1::bigint
) r
WHERE s.id = r.id AND s.position <> r.pos
`

// CompactStatusPositions renumbers positions 0..n-1 keeping the current order.
func (q *Queries) CompactStatusPositions(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, compactStatusPositions, projectID)
	return err
}

const countStatusIssues = `-- name: CountStatusIssues :one
SELECT count(*) FROM issues WHERE status_id = $1
`

func (q *Queries) CountStatusIssues(ctx context.Context, statusID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStatusIssues, statusID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatus = `-- name: CreateStatus :one
INSERT INTO statuses (project_id, name, category, position, wip_limit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, category, position, wip_limit, created_at
`

type CreateStatusParams struct {
	ProjectID int64  `db:"project_id"`
	Name      string `db:"name"`
	Category  string `db:"category"`
	Position  int32  `db:"position"`
	WipLimit  *int32 `db:"wip_limit"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, createStatus,
		arg.ProjectID,
		arg.Name,
		arg.Category,
		arg.Position,
		arg.WipLimit,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM statuses WHERE id = $1
`

func (q *Queries) DeleteStatus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStatus, id)
	return err
}

const getStatus = `-- name: GetStatus :one
SELECT id, project_id, name, category, position, wip_limit, created_at FROM statuses WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id int64) (Status, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getStatusForKeyShare = `-- name: GetStatusForKeyShare :one
SELECT id, project_id, name, category, position, wip_limit, created_at FROM statuses WHERE id = $1 FOR KEY SHARE
`

// GetStatusForKeyShare reads a status with the FOR KEY SHARE lock a foreign-key check takes.
// Issue writes that point an issue at a status use it, so a concurrent DeleteStatus or
// category change (which hold LockStatus) either finishes first — and the write then finds
// the status gone or reads its new category — or waits for the write and then includes the
// issue (moving it along, or re-deriving its resolved_at).
func (q *Queries) GetStatusForKeyShare(ctx context.Context, id int64) (Status, error) {
	row := q.db.QueryRow(ctx, getStatusForKeyShare, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.CreatedAt,
	)
	return i, err
}

const listStatuses = `-- name: ListStatuses :many

SELECT id, project_id, name, category, position, wip_limit, created_at FROM statuses WHERE project_id = $1 ORDER BY position, id
`

// Workflow statuses (board columns).
func (q *Queries) ListStatuses(ctx context.Context, projectID int64) ([]Status, error) {
	rows, err := q.db.Query(ctx, listStatuses, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Status{}
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Category,
			&i.Position,
			&i.WipLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusesByIDs = `-- name: ListStatusesByIDs :many
SELECT id, project_id, name, category, position, wip_limit, created_at FROM statuses WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListStatusesByIDs(ctx context.Context, ids []int64) ([]Status, error) {
	rows, err := q.db.Query(ctx, listStatusesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Status{}
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Category,
			&i.Position,
			&i.WipLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStatus = `-- name: LockStatus :one
SELECT id, project_id, name, category, position, wip_limit, created_at FROM statuses WHERE id = $1 FOR UPDATE
`

// LockStatus locks a status that is about to be changed or deleted. FOR UPDATE conflicts
// with GetStatusForKeyShare (a plain category change would only take FOR NO KEY UPDATE,
// which issue writers do not wait for).
func (q *Queries) LockStatus(ctx context.Context, id int64) (Status, error) {
	row := q.db.QueryRow(ctx, lockStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.CreatedAt,
	)
	return i, err
}

const logStatusMigration = `-- name: LogStatusMigration :exec
INSERT INTO activities (project_id, issue_id, issue_key, actor_id, action, field, old_value, new_value)
SELECT i.project_id, i.id, i.key, $1::bigint, 'issue.updated', 'status', $2::text, $3::text
FROM issues i
WHERE i.status_id = $4
`

type LogStatusMigrationParams struct {
	ActorID      int64  `db:"actor_id"`
	OldName      string `db:"old_name"`
	NewName      string `db:"new_name"`
	FromStatusID int64  `db:"from_status_id"`
}

// LogStatusMigration records the status change of every issue about to be moved by
// MoveIssuesToStatus. Run it first.
func (q *Queries) LogStatusMigration(ctx context.Context, arg LogStatusMigrationParams) error {
	_, err := q.db.Exec(ctx, logStatusMigration,
		arg.ActorID,
		arg.OldName,
		arg.NewName,
		arg.FromStatusID,
	)
	return err
}

const moveIssuesToStatus = `-- name: MoveIssuesToStatus :exec
UPDATE issues
SET status_id   = $1,
    resolved_at = CASE WHEN $2::bool THEN COALESCE(resolved_at, now()) ELSE NULL END,
    updated_at  = now()
WHERE status_id = $3
`

type MoveIssuesToStatusParams struct {
	ToStatusID   int64 `db:"to_status_id"`
	ToDone       bool  `db:"to_done"`
	FromStatusID int64 `db:"from_status_id"`
}

func (q *Queries) MoveIssuesToStatus(ctx context.Context, arg MoveIssuesToStatusParams) error {
	_, err := q.db.Exec(ctx, moveIssuesToStatus, arg.ToStatusID, arg.ToDone, arg.FromStatusID)
	return err
}

const nextStatusPosition = `-- name: NextStatusPosition :one
SELECT COALESCE(MAX(position) + 1, 0)::int FROM statuses WHERE project_id = $1
`

func (q *Queries) NextStatusPosition(ctx context.Context, projectID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextStatusPosition, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reorderStatuses = `-- name: ReorderStatuses :exec
UPDATE statuses s
SET position = (o.ord - 1)::int
FROM unnest($2::bigint[]) WITH ORDINALITY AS o(id, ord)
WHERE s.id = o.id AND s.project_id = $1::bigint
`

type ReorderStatusesParams struct {
	ProjectID int64   `db:"project_id"`
	Ids       []int64 `db:"ids"`
}

// ReorderStatuses sets position = index in `ids` (0-based). `ids` must be a permutation of
// the project's status ids (validated by the service).
func (q *Queries) ReorderStatuses(ctx context.Context, arg ReorderStatusesParams) error {
	_, err := q.db.Exec(ctx, reorderStatuses, arg.ProjectID, arg.Ids)
	return err
}

const syncResolvedAtForStatus = `-- name: SyncResolvedAtForStatus :exec
UPDATE issues
SET resolved_at = CASE WHEN $1::bool THEN COALESCE(resolved_at, now()) ELSE NULL END
WHERE status_id = $2
`

type SyncResolvedAtForStatusParams struct {
	Done     bool  `db:"done"`
	StatusID int64 `db:"status_id"`
}

// SyncResolvedAtForStatus re-derives resolved_at after a status changed category.
func (q *Queries) SyncResolvedAtForStatus(ctx context.Context, arg SyncResolvedAtForStatusParams) error {
	_, err := q.db.Exec(ctx, syncResolvedAtForStatus, arg.Done, arg.StatusID)
	return err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE statuses SET name = $2, category = $3, wip_limit = $4 WHERE id = $1 RETURNING id, project_id, name, category, position, wip_limit, created_at
`

type UpdateStatusParams struct {
	ID       int64  `db:"id"`
	Name     string `db:"name"`
	Category string `db:"category"`
	WipLimit *int32 `db:"wip_limit"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, updateStatus,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.WipLimit,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.CreatedAt,
	)
	return i, err
}
