// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at, updated_at, token_version
`

type CreateUserParams struct {
	Email        string `db:"email"`
	Name         string `db:"name"`
	PasswordHash string `db:"password_hash"`
}

// Users. Emails are always stored lower-cased (the service normalises input).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserTokenVersion = `-- name: GetUserTokenVersion :one
SELECT token_version FROM users WHERE id = $1
`

// GetUserTokenVersion returns the token version access tokens of the user must carry.
func (q *Queries) GetUserTokenVersion(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getUserTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users
WHERE $1::text = ''
   OR name ILIKE '%' || $1::text || '%'
   OR email ILIKE '%' || $1::text || '%'
ORDER BY lower(name), id
LIMIT $2::int
`

type SearchUsersParams struct {
	Pattern    string `db:"pattern"`
	MaxResults int32  `db:"max_results"`
}

// SearchUsers matches name or e-mail case-insensitively. `pattern` must already have
// LIKE wildcards escaped; an empty pattern returns the first users by name.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Pattern, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name          = $1,
    password_hash = $2,
    token_version = token_version + CASE WHEN $3::bool THEN 1 ELSE 0 END,
    updated_at    = now()
WHERE id = $4
RETURNING id, email, name, password_hash, created_at, updated_at, token_version
`

type UpdateUserParams struct {
	Name         string `db:"name"`
	PasswordHash string `db:"password_hash"`
	RevokeTokens bool   `db:"revoke_tokens"`
	ID           int64  `db:"id"`
}

// UpdateUser writes the name and password hash. revoke_tokens increments token_version,
// which invalidates every access token issued before (used when the password changes).
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.PasswordHash,
		arg.RevokeTokens,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}
