// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at, updated_at, token_version
`

type CreateUserParams struct {
	Email        string `db:"email"`
	Name         string `db:"name"`
	PasswordHash string `db:"password_hash"`
}

// Users. Emails are always stored lower-cased (the service normalises input).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserTokenVersion = `-- name: GetUserTokenVersion :one
SELECT token_version FROM users WHERE id = $1
`

// GetUserTokenVersion returns the token version access tokens of the user must carry.
func (q *Queries) GetUserTokenVersion(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getUserTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, password_hash, created_at, updated_at, token_version FROM users
WHERE $1::text = ''
   OR name ILIKE '%' || $1::text || '%'
   OR email ILIKE '%' || $1::text || '%'
ORDER BY lower(name) COLLATE "und-x-icu", id
LIMIT $2::int
`

type SearchUsersParams struct {
	Pattern    string `db:"pattern"`
	MaxResults int32  `db:"max_results"`
}

// SearchUsers matches name or e-mail case-insensitively. `pattern` must already have
// LIKE wildcards escaped; an empty pattern returns the first users by name (Unicode root
// collation, see labels.sql).
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Pattern, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name          = COALESCE($1::text, name),
    password_hash = COALESCE($2::text, password_hash),
    token_version = token_version + CASE WHEN $2::text IS NULL THEN 0 ELSE 1 END,
    updated_at    = now()
WHERE id = $3
  AND token_version = $4
  AND ($2::text IS NULL OR password_hash = $5)
RETURNING id, email, name, password_hash, created_at, updated_at, token_version
`

type UpdateUserParams struct {
	Name                 *string `db:"name"`
	PasswordHash         *string `db:"password_hash"`
	ID                   int64   `db:"id"`
	TokenVersion         int32   `db:"token_version"`
	VerifiedPasswordHash string  `db:"verified_password_hash"`
}

// UpdateUser changes the name and/or the password hash; a NULL argument keeps that column,
// so a concurrent update of the other column is never overwritten with a stale value. It
// writes only while token_version is still the caller's (a password change committed since
// revoked the caller's token), and a new password hash only while the stored one is still
// verified_password_hash (the hash the current password was checked against); otherwise no
// row is returned. A new password hash increments token_version, which invalidates every
// access token issued before.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.PasswordHash,
		arg.ID,
		arg.TokenVersion,
		arg.VerifiedPasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenVersion,
	)
	return i, err
}
